import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-2 md:mx-8 xl:mx-24 2xl:mx-36`}
      >
        <header className="hidden md:block">
          <nav className="flex justify-between items-end h-20 pb-2 border-b-1 border-b-violet-300">
            <div className="flex-1">
              <a href="/products" className="mr-16">All</a>
              <a href="/products/favorites">Favorites</a>
            </div>

            <a href="/" className="flex-1 font-black text-center uppercase">Hand Crafted Haven</a>

            <a href="/auth/login" className=" flex-1 text-right">Login</a>
          </nav>
        </header>
        <main>
          {children}
        </main>
        <footer className="bg-violet-500 text-white p-8">
          <p className="font-bold italic">Handcrafted Haven 2025</p>
        </footer>
      </body>
    </html>
  );
}
