import type { Metadata } from "next";
import Link from "next/link";
import { Montserrat, Geist_Mono, Lato, Montaga } from "next/font/google";
import "./globals.css";
import { auth } from "../../auth";
import { logout } from "./lib/actions";

const lato = Lato({
  weight: [
      "100", // Thin
      "300", // Light
      "400", // Regular
      "700", // Bold
      "900", // Black
    ],
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const montserrat = Montserrat({
  weight: [
      "100", // Thin
      "200", // Extra Light
      "300", // Light
      "400", // Regular
      "500", // Medium
      "600", // Semi Bold
      "700", // Bold
      "800", // Extra Bold
      "900", // Black
    ],
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

const montaga = Montaga({
  weight: [
      "400", // Regular
    ],
  subsets: ["latin"],
  variable: "--font-number",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" className={`antialiased mx-2 md:mx-8 xl:mx-24 2xl:mx-36`}>
      <body className="font-body">
        <header className="hidden md:block">
          <nav className={`flex justify-between items-end h-20 pb-2 border-b-1 border-b-violet-300 font-heading`}>
            <div className="flex-1">
              <Link href="/items" className="mr-16">All</Link>
              <Link href="/items/favorites">Favorites</Link>
            </div>

            <Link href="/" className="flex-1 font-black text-center uppercase">Hand Crafted Haven</Link>

            <div className="flex justify-end flex-1 text-right">
              {session?.user ? (
                <>
                  <Link href="/seller/items" className="mr-16">My Items</Link>
                  <div>
                    <form action={logout}>
                      <button
                        type="submit"
                        className="hover:underline cursor-pointer"
                      >
                        Logout
                      </button>
                    </form>
                  </div>
                </>
              ):(
                <>
                  <Link href="/auth/login">Login</Link>
                </>
              )}
            </div>
          </nav>
        </header>
        <main>
          {children}
        </main>
        <footer className="bg-violet-700 text-white p-8 font-heading">
          <p className="font-bold italic">Handcrafted Haven 2025</p>
        </footer>
      </body>
    </html>
  );
}
