import type { Metadata } from "next";
import Link from "next/link";
import { Montserrat, Geist_Mono, Lato, Montaga } from "next/font/google";
import "./globals.css";
import { auth } from "../../auth";
import { logout } from "./lib/actions";

const lato = Lato({
  weight: [
      "100", // Thin
      "300", // Light
      "400", // Regular
      "700", // Bold
      "900", // Black
    ],
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const montserrat = Montserrat({
  weight: [
      "100", // Thin
      "200", // Extra Light
      "300", // Light
      "400", // Regular
      "500", // Medium
      "600", // Semi Bold
      "700", // Bold
      "800", // Extra Bold
      "900", // Black
    ],
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

const montaga = Montaga({
  weight: [
      "400", // Regular
    ],
  subsets: ["latin"],
  variable: "--font-number",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" className={`antialiased mx-2 md:mx-8 xl:mx-24 2xl:mx-36`}>
      <body className="font-body">
        <div className="text-center md:hidden">
          <Link href="/" className="flex-1 font-heading font-black text-center uppercase">Hand Crafted Haven</Link>
        </div>
        <header className="overflow-x-scroll">
          <nav className={`flex justify-between items-end h-20 pb-2 border-b-1 border-b-violet-300 font-heading`}>

            {session?.user ? (
              <>
                <div className="flex justify-around flex-1">
                  <Link href="/seller/items" className="nav-item">My Items</Link>
                  <Link href="/seller/orders" className="nav-item">Orders</Link>
                </div>

                <Link href="#" className="hidden md:block flex-1 font-black text-center uppercase">Hand Crafted Haven</Link>

                <div className="flex justify-around flex-1">
                  <Link href="/seller/profile" className="nav-item">Profile</Link>

                  <form action={logout}>
                    <button
                      type="submit"
                      className="hover:underline cursor-pointer"
                    >
                      Logout
                    </button>
                  </form>
                </div>
              </>) : (
                <>
                  <div className="flex justify-around flex-1">
                    <Link href="/items" className="nav-item">All</Link>
                    <Link href="/items/favorites" className="nav-item">Favorites</Link>
                  </div>

                  <Link href="/" className="hidden md:block flex-1 font-black text-center uppercase">Hand Crafted Haven</Link>

                  <div className="flex justify-end flex-1 md:justify-end  md:text-right">
                    <Link href="/auth/login" className="nav-item">Login</Link>
                  </div>
                </>
            )}

          </nav>
        </header>
        <main>
          {children}
        </main>
        <footer className="bg-violet-700 text-white p-8 font-heading">
          <p className="font-bold italic">Handcrafted Haven 2025</p>
        </footer>
      </body>
    </html>
  );
}
